env:
  es2021: true
  jest: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jsdoc/recommended
  - plugin:promise/recommended
  - prettier
  - plugin:prettier/recommended  # Enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
  - plugin:eslint-comments/recommended

settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
  # This part is required to work with eslint, the rest is already setup to use import
  import/resolver:
    typescript:

parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.test.json'
  tsconfigRootDir: '.'
  ecmaVersion: 2020
  sourceType: "module"

plugins:
  - '@typescript-eslint'
  - import
  - jsdoc
  - promise

root: true

rules:
  # https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html
  import/prefer-default-export: off
  import/no-default-export: error