# Add rules here to build your software
# See https://docs.bazel.build/versions/master/build-ref.html#BUILD_files

load("//bazel:setup.bzl", "ts_setup")

ts_setup(
  name = "main",
  srcs = [
    'main.ts'
  ],
)
